# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2
project_name: lantern-headless
metadata:
  maintainers:
    - "Lantern Team <dev@getlantern.org>"
  description: Lantern Headless Client
  homepage: "https://github.com/getlantern/lantern-headless-client"
  license: "GPL"

signs:
  - cmd: cosign
    stdin: ""
    signature: "${artifact}.sigstore.json"
    args:
      - "sign-blob"
      - "--key=cosign.key"
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: all
builds:
  - # we are not building using goreleaser, but using make, so here we just use the prebuilt binaries
    builder: prebuilt

    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - mips64
      - arm64
      - "386"
      #- armv6
      #- armv7

    ignore:
      - goos: windows
        goarch: arm64
      - goos: linux
        goarch: "386"
    prebuilt:
      path: build/lantern-headless-{{ .Arch }}-{{ .Os }}

    binary: lantern-headless

universal_binaries:
  - replace: true

archives:
  - formats: ["tar.gz"]
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: ["zip"]
    files:
      - LICENSE
      - README.md
      - src: ./scripts/lantern-headless.service

notarize:
  macos:
    - enabled: true
      sign:
        certificate: "{{.Env.MACOS_SIGN_P12}}"
        password: "{{.Env.MACOS_SIGN_PASSWORD}}"
      notarize:
        key: "{{.Env.MACOS_P8}}"
        key_id: "{{.Env.MACOS_KEY_ID}}"
        issuer_id: "{{.Env.MACOS_ISSUER_ID}}"
        # wait: true
        # timeout: 50m


dmg:
  - name: "lantern-headless-{{.Arch}}"
    replace: true

msi:
  - name: "lantern-headless-{{.MsiArch}}"
    replace: true
    wxs: ./scripts/setup.wsx

nfpms:
  - package_name: "lantern-headless"
    formats:
      - apk
      - deb
      - rpm
      - ipk
      - archlinux
    section: "default"
    maintainer: "Lantern Team <dev@getlantern.org>"
    description: |
      Lantern Headless Client
    vendor: "Brave New Software"
    homepage: "https://github.com/getlantern/lantern-headless-client"
    license: "GPL"
    contents:
      - src: ./scripts/lantern-headless.service
        dst: /etc/lantern-headless/lantern-headless.service
        file_info:
          mode: 0600
          owner: root
          group: root
      - src: ./scripts/lantern-headless.sysvinit
        dst: /etc/lantern-headless/lantern-headless.sysvinit
        file_info:
          mode: 0700
          owner: root
          group: root
    scripts:
      postinstall: ./scripts/postinstall
      preremove: ./scripts/preremove
      preinstall: ./scripts/preinstall
    archlinux:
      packager: Lantern Team <dev@getlantern.org>
      scripts:
        postupgrade: ./scripts/postinstall

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  replace_existing_artifacts: true

furies:
  - account: getlantern
    formats:
      - deb
      - rpm

dockers_v2:
  - id: "lantern-headless"
    images:
      - "getlantern/lantern-headless"
    tags:
      - "{{ .Tag }}"
      - "latest"

dockerhub:
  - images:
      - getlantern/lantern-headless
    username: getlantern
    secret_name: DOCKER_PASSWORD
    full_description:
      from_file:
        path: ./README.md

aurs:
  - name: lantern-headless-bin
    homepage: "https://github.com/getlantern/lantern-headless-client"
    maintainers:
      - "Lantern Team <dev@getlantern.org>"
    description: |
      Lantern Headless Client
    license: "GPL"
    git_url: "ssh://aur@aur.archlinux.org/lantern-headless-bin.git"
    private_key: "{{ .Env.AUR_KEY }}"
    package: |
      install -Dm755 "./lantern-headless" "${pkgdir}/usr/bin/lantern-headless"
      install -Dm644 "./scripts/lantern-headless.service" "${pkgdir}/usr/lib/systemd/user/lantern-headless.service"

scoops:
  - use: msi
    repository:
      token: "{{ .Env.TAP_BUCKET_TOKEN }}"
      name: lantern-headless-client-scoop-bucket
      owner: getlantern
      branch: main

homebrew_casks:
  -
    repository:
      token: "{{ .Env.TAP_BUCKET_TOKEN }}"
      name: lantern-headless-client-brew-tap
      owner: getlantern
      branch: main
