# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LanternHeadless < Formula
  desc "Lantern Headless Client"
  homepage "https://github.com/getlantern/lantern-headless-client"
  version "1.0.19"
  license "GPL"

  on_macos do
    url "https://github.com/getlantern/lantern-headless-client/releases/download/v1.0.19/lantern-headless-all.dmg"
    sha256 "50087c3daa5e0c5c8dcbe86832bb2e5efaff4d0e2d2445d8d1150e1780111f02"

    def install
      bin.install "lantern-headless"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/getlantern/lantern-headless-client/releases/download/v1.0.19/lantern-headless_1.0.19_linux_amd64.tar.gz"
        sha256 "cd4068d0f2e426b6a24c28754f7b02f0ab5263137395fcbaffda1f24d08adc8f"

        def install
          bin.install "lantern-headless"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/getlantern/lantern-headless-client/releases/download/v1.0.19/lantern-headless_1.0.19_linux_arm64.tar.gz"
        sha256 "ed887ad144a854ec73e457a3667f4897e2a9c0f048fcabb097ac9a77a9aaa2fb"

        def install
          bin.install "lantern-headless"
        end
      end
    end
  end
end
