# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LanternHeadless < Formula
  desc ""
  homepage ""
  version "1.0.18"

  on_macos do
    url "https://github.com/getlantern/lantern-headless-client/releases/download/v1.0.18/lantern-headless-all.dmg"
    sha256 "08abe66f01b4cd432c60afe115bb408ec338d7b40d45c03fa45d2b81d0ce3c8e"

    def install
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/getlantern/lantern-headless-client/releases/download/v1.0.18/lantern-headless_1.0.18_linux_amd64.tar.gz"
        sha256 "4729a8db1d56038f2dcabdbe627dc0780bed5425a518d5c7b3de91bb38d67201"

        def install
          bin.install "lantern-headless"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/getlantern/lantern-headless-client/releases/download/v1.0.18/lantern-headless_1.0.18_linux_arm64.tar.gz"
        sha256 "4006e7420ff09c6902c10e2c1a0727b17ffd594e19fdc29ad2ea157900767096"

        def install
          bin.install "lantern-headless"
        end
      end
    end
  end
end
